### ISSUE TITLE
DistanceQuerySpecBuilder causes NPE when geo function is part of math expression

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j-storage#87]
On a GeoSPARQL query containing this construct:

    BIND( (geof:distance(?coord1, ?coord2, uom:metre) / 1000) as ?dist)

query execution fails with a `NullPointerException`:

 
```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.rdf4j.query.algebra.TupleFunctionCall.addArg(TupleFunctionCall.java:58)
	at org.eclipse.rdf4j.sail.lucene.DistanceQuerySpecBuilder$1.meet(DistanceQuerySpecBuilder.java:116)
	at org.eclipse.rdf4j.query.algebra.StatementPattern.visit(StatementPattern.java:211)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:102)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetBinaryTupleOperator(AbstractQueryModelVisitor.java:607)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:343)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:81)
	at org.eclipse.rdf4j.query.algebra.Extension.visitChildren(Extension.java:103)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetUnaryTupleOperator(AbstractQueryModelVisitor.java:687)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:241)
	at org.eclipse.rdf4j.query.algebra.Extension.visit(Extension.java:92)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:81)

```
Root cause is that `DistanceQuerySpecBuilder` in processing the `FunctionCall` object only checks if the _direct_ parent is an `ExtensionElem` (line 66 and further). In this case, since we divide the outcome by 1000, the direct parent is a `MathExpr`, and we should traverse one further level up in the algebra model to get at the `ExtensionElem` and find the variable to which the function outcome should be bound.

Confirmed locally that by simply removing the division, the query works as expected.

**Comment by jeenbroekstra** [comment]
Thanks for that, I like that, that makes a lot of sense. I'll try and pick this up later this week.
